package sorters;

public enum TypeSorters {
    BUBBLE_SORT_EMERGE,
    BUBBLE_SORT_DROWNS,
    QUICK_SORT,
    ARRAYS_SORT,
    MERGE_WITH_BUBBLE_SORT_DROWNS,
    MERGE_WITH_BUBBLE_SORT_EMERGE,
    MERGE_WITH_QUICK_SORT,
    MERGE_WITH_ARRAYS_SORT
}
